name: Verificacion de pruebas cuando se hace merge a develop
on:
  push:
    branches: [ develop ]
jobs:
  pruebas:
    name: Pruebas Unitarias
    runs-on: Ubuntu-20.04
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lanzas todas las pruebas unitarias
      id: lanzar-pruebas-unitarias
      run: python -m unittest -v tests/*.py
    - name: Validar resultado si las pruebas tienen errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron por favor verifiquelas
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Validar resultado si las pruebas no tienen errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Felicitaciones! La ejecucion de todas las pruebas unitarias fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
    - name: Calcular de cubrimiento de las pruebas unitarias
      id: cubrimiento
      run: |
          coverage run -m unittest tests/*.py
          coverage report -m